### ISSUE TITLE
TypeError: rule.listener is not a function

### ISSUE THREAD

**Issue by roballsopp** [cytoscape/cytoscape.js-automove#21]
I can't seem to get this extension to work. On load I immediately get an error:
```
Uncaught TypeError: rule.listener is not a function
    at addRule (cytoscape-automove.js:388)
    at Core.automove (cytoscape-automove.js:489)
    ...
```
Here's what my setup looks like:
```javascript
import cytoscape from 'cytoscape';
import automove from 'cytoscape-automove';

cytoscape.use(automove);

export default function CytoscapeGraph({ height }) {
	const graphRef = React.useRef();

	React.useEffect(() => {
		const cy = cytoscape({
			userZoomingEnabled: false,
			userPanningEnabled: false,
			style: { ... },
		});

		if (graphRef.current) {
			// this is where all the nodes and edges are added using cy.add()
			buildGraphFromActions(cy, actions);
			cy.mount(graphRef.current);
			cy.layout({ ... }).run();
			cy.automove({
				nodesMatching: cy.nodes(),
				reposition: node => {
					const pos = node.position();
					return { y: pos.y };
				},
			});
			cy.fit(cy.elements());
		}
		...
		return () => {
			cy.destroy();
		};
	}, [...]);

	return <div ref={graphRef} />;
}
```
If I add a `when: update => update()`, things don't blow up, but I don't see my `reposition` function get called at all. Does all this have something to do with the fact that I am building my graph after my initial `cytoscape({ ... })` call?

**Comment by maxkfranz** [comment]
Are you able to reproduce your issue in a more minimal way without React, say in a slightly modified version of the demo in the repo?

**Comment by manotoor** [comment]
@maxkfranz looks like the function to get rule listener is hard coded for

>   'mean' => put the node in the average position of its neighbourhood
>  'viewport' => keeps the node body within the viewport
>   'drag' => matching nodes are effectively dragged along

and defaults to rule.when if those are not given.

while the github readme states that you can pass a function 

> // specify how a node's position should be updated with one of
>   // - function( node ){ return { x: 1, y: 2 }; } => put the node where the function returns
>   // - { x1, y1, x2, y2 } => constrain the node position within the bounding box (in model co-ordinates)
>   // - { x1, y1, x2, y2, type: 'inside' } => constrain the node position within the bounding box (in model co-ordinates)
>   // - { x1, y1, x2, y2, type: 'outside' } => constrain the node position outside the bounding box (in model co-ordinates)

However rule.when is undefined by default, so rule.listen is undefined

**Comment by maxkfranz** [comment]
@manotoor, do you have a test case that reproduces the error you mentioned?

**Comment by srinivasrk** [comment]
I have a similar issue as well

```
this.cy.automove({
      nodesMatching: this.cy.nodes(),
      reposition: node => {
        const pos = node.position();
        return { y: pos.y };
      },
      when: undefined
    });
```

shows the following error:

```
index.mjs:9411 Uncaught TypeError: rule.listener is not a function
    at addRule (index.mjs:9411)
    at Core.automove (index.mjs:9502)
    at SMPLE._configureAutoMove (index.mjs:9697)
    at index.mjs:9688
```

**Comment by SheereenHamza** [comment]
Hi,

Has there been any update on this ? 
I get the same error when given a **function for resposition**
