### ISSUE TITLE
ES import not working and 'this' not defined

### ISSUE THREAD

**Issue by cliffchens** [cytoscape/cytoscape.js-automove#23]
Hi, I am a beginner programmer and I have two problems. 

One, I cannot import import automove using the ES `import` functionality. I am trying to serve a static HTML page containing JS scripts using NodeJS and ExpressJS and in one of my public script files I make the call:

`import automove from './cytoscape-automove.js'`. 

and I get the error: `Uncaught SyntaxError: The requested module './cytoscape-automove.js' does not provide an export named 'automove'`. 

The second problem is if I try to load cytoscape-automove.js through an HTML `<script type = 'module'>` tag, I get the error: `cytoscape-automove.js:9 Uncaught TypeError: Cannot set property 'cytoscapeAutomove' of undefined`. 

Looking through the code, I see that an argument of `this` is provided to the `webpackUniversalModuleDefinition` function and I would naively think that `this` is just a reference to the global object but unfortunately I am not familiar with webpack and how it bundles assets.

**Comment by cliffchens** [comment]
I see. This is a bit confusing though since the usage instructions in the README file states that I can import the extension using the native ESM `import`.

**Comment by maxkfranz** [comment]
The majority of people use tools like webpack that allow for ESM with CJS dependencies (all of npm is in CJS).  If ESM weren’t mentioned in the readme, then it would be confusing for those consumers.
