### ISSUE TITLE
Cannot drag successors of arbitrary node

### ISSUE THREAD

**Issue by Ben-Pattinson** [cytoscape/cytoscape.js-automove#24]
I want to be able to drag an arbitrary node, and have it's successors move with it. This is a generally desirable thing in directed graphs (I don't think it's standard functionality though). 
I have many plausible ways this might work, but don't; probably due to the execution order of click events. This is the neatest: 
`cy.automove({nodesMatching: function(node){return node.selected()? node.successors():null}, reposition:'drag',dragWith: cy.nodes()})`

Sounds plausible, but nothing is ever detected as being selected. There is a similar problem with this slightly cruder approach: 
```
cy.nodes().on('vmousedown', function(e){
cy.automove("destroy");
  var ele = e.target;
  console.log('clicked ' + ele.id());
cy.automove({nodesMatching: cy.$id(ele.id()).successors(), reposition:'drag',dragWith: cy.$id(ele.id())})
});
```

So, is there a way to achieve this without resorting to adding every permutation of nodes and successors, as rules?  Or do we need a code change?

Thanks

**Comment by maxkfranz** [comment]
If you think the API is insufficient for this use case -- or if it could be made easier -- you're welcome to propose API additions.  What do you think would fit well?
