### ISSUE TITLE
Move 2 nodes in same y coordinate and keep same distance in x

### ISSUE THREAD

**Issue by emmasuzuki** [cytoscape/cytoscape.js-automove#6]
Hi,

In the demo, node #e and #f is restricts to have same y. 
I would like to tweak this to keep the same distance in horizontal.

I tried 
```javascript
// Make only #e grabbable but not #f, when I move e, f should always follow e.
{ data: { id: 'f' }, selectable: false, grabbable: false }

cy.automove({
  nodesMatching: '#e, #f',
  reposition: function( node ){
     var pos = node.position();
     if( node.grabbed() ){ return pos; }
       var otherNode = eAndF.not( node );
       return {
         x: otherNode.position('x') + 40,
	 y: otherNode.position('y')
      };
  },
  when: 'matching'
});
```

However, this seems to trigger 'matching' rule recursively and results in infinite loop.

I tried to write custom when function but I could not figure out how to bind to some event. 
If I don't bind, this only called once and it does not listen for any event. 
```
when: function(update) {
  // some rule
  update();
}
```

How can I achieve #f node follow #e in same y coordinate and same horizontal distance?

**Comment by ajoslin103** [comment]
did you get this working?

**Comment by maxkfranz** [comment]
Your spec doesn't make sense.  You've overconstrained the system.  `e` must be to the right of `f`, which must be to the right of `e`...

You should derive your spec from the distance equation instead: https://en.wikipedia.org/wiki/Distance#Geometry

**Comment by emmasuzuki** [comment]
I would like to make `f` to be always right of `e` with some px apart (thinking as clickable&hoverable accessory other than label).
is this still over-constraining?
