### ISSUE TITLE
demo.html doesn't work, or I don't understand it

### ISSUE THREAD

**Issue by ajoslin103** [cytoscape/cytoscape.js-automove#7]
I would like to use this extension to enable dragging of groups of nodes

but leaving aside how I will select them for the moment, I can't get anything to work.

when I download and run your demo.html -- nothing seems to work.

#mid starts way off-screen 

#d isn't limited to a box

#e and #f aren't bounded and don't move together

#g can be dragged out of the window, then zoom out shows it again

(tried chrome 59 over mac os x 10.12.3)
(tried safari 10.0.3 over mac os x 10.12.3)
(tried opera 43 over mac os x 10.12.3)

**Comment by maxkfranz** [comment]
I just pulled on master and the demo is working on my machine.  Please provide more information to reproduce your issue

**Comment by ajoslin103** [comment]
ah!  I didn't have the cytoscape-automove.js file as a sibling to the demo.html file -- I had [mistakenly] thought it was being pulled dynamically.  

things are working for me now - thanks!

automove is really going to put the icing on the cake for the product I'm building, so thanks a lot for your work !!

**Comment by maxkfranz** [comment]
Yes, you have to use npm or download the file manually.  Glad it worked out
