### ISSUE TITLE
automove an arbitrary collection of elements

### ISSUE THREAD

**Issue by ajoslin103** [cytoscape/cytoscape.js-automove#8]
What would be the recommended way to automove an arbitrary collection of elements?

**Comment by ajoslin103** [comment]
figured out how to support dragging a selection - what I am hoping to do is (when using dagre layout) to preserve the users adjustments and re-apply them after the layout re-draws 

is this even possible?

**Comment by maxkfranz** [comment]
You can dynamically create rules and the rules are dynamic as they are specified by functions.  You can disable and enable rules as well.

But it sounds like you could just lock the nodes.  

In any case, you'll have to make sure your feature is well defined and examine which parts of the APIs would suit it best.

**Comment by ajoslin103** [comment]
ok, thanks!
